"""Routes for signal-service (Mojo)."""

from typing import Optional

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import StreamingResponse
import asyncio
import json

router = APIRouter()


@router.get("/alerts")
async def get_alerts(
    request: Request,
    limit: int = 100,
    offset: int = 0,
    symbol: Optional[str] = None,
    sector: Optional[str] = None,
):
    """Get alerts from signal-service."""
    try:
        client = request.app.state.signal_service
        response = await client.get_alerts(
            limit=limit,
            offset=offset,
            symbol=symbol,
            sector=sector,
        )
        return response
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Signal service error: {str(e)}")


@router.get("/alerts/stream")
async def stream_alerts(request: Request):
    """Server-Sent Events stream of real-time alerts.

    This endpoint streams new alerts as they are generated by signal-service.
    """

    async def event_generator():
        """Generate SSE events."""
        try:
            # Send initial connection message
            yield f"data: {json.dumps({'event': 'connected', 'message': 'SSE stream started'})}\n\n"

            # TODO: Implement actual event streaming from Mojo signal-service
            # For now, this is a placeholder that sends heartbeats

            while True:
                if await request.is_disconnected():
                    break

                # Heartbeat every 30 seconds
                await asyncio.sleep(30)
                yield f": heartbeat\n\n"

                # TODO: Get events from signal-service and yield them
                # Example:
                # event = await client.get_next_event()
                # yield f"data: {json.dumps(event)}\n\n"

        except Exception as e:
            yield f"event: error\ndata: {json.dumps({'error': str(e)})}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


@router.post("/generate")
async def generate_signals(
    request: Request,
    symbol: str,
    indicators: Optional[dict] = None,
    news_context: Optional[dict] = None,
):
    """Generate trading signals for a symbol."""
    try:
        client = request.app.state.signal_service
        response = await client.generate_signals(
            symbol=symbol,
            indicators=indicators,
            news_context=news_context,
        )
        return response
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Signal service error: {str(e)}")


@router.get("/patterns/{symbol}")
async def get_patterns(
    request: Request,
    symbol: str,
    pattern_types: Optional[str] = None,
):
    """Get pattern matches for a symbol.

    Args:
        symbol: Stock symbol
        pattern_types: Comma-separated list of pattern types (optional)
    """
    try:
        client = request.app.state.signal_service

        pattern_list = pattern_types.split(",") if pattern_types else None

        response = await client.get_patterns(
            symbol=symbol,
            pattern_types=pattern_list,
        )
        return response
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Signal service error: {str(e)}")
